In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("placement.csv")

In [3]:
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [5]:
df.shape

(200, 2)

In [6]:
df.isnull().sum()

cgpa       0
package    0
dtype: int64

In [23]:
import numpy as np

In [24]:
import pandas as pd

In [25]:
import seaborn as sns

In [26]:
import matplotlib.pyplot as plt

In [27]:
import warnings
warnings.filterwarnings

<function warnings.filterwarnings(action, message='', category=<class 'Warning'>, module='', lineno=0, append=False)>

In [28]:
df = pd.read_csv("Titanic-Dataset.csv")

In [25]:
df.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                   

In [26]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [29]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

C:\Users\Deepak joshi\AppData\Local\Temp\ipykernel_6388\694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)


In [30]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [31]:
df.drop(['Cabin'],axis=1,inplace=True)

In [32]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [33]:
df.dropna(subset=['Embarked'],inplace=True)

In [34]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [38]:
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])


In [37]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    0  38.0      1      0  71.2833         0
2            3         1       3    0  26.0      0      0   7.9250         2
3            4         1       1    0  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2

In [35]:
df.drop(['Name'],axis=1,inplace=True)


In [45]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch            Ticket  \
0            1         0       3    1  22.0      1      0         A/5 21171   
1            2         1       1    0  38.0      1      0          PC 17599   
2            3         1       3    0  26.0      0      0  STON/O2. 3101282   
3            4         1       1    0  35.0      1      0            113803   
4            5         0       3    1  35.0      0      0            373450   

      Fare  Embarked  
0   7.2500         2  
1  71.2833         0  
2   7.9250         2  
3  53.1000         2  
4   8.0500         2

In [17]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [39]:
x = df.drop("Survived",axis=1)
y = df["Survived"]

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test ,y_train,y_test = train_test_split(x,y,test_size=2,random_state=42)

In [20]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch            Ticket  \
0            1         0       3    1  22.0      1      0         A/5 21171   
1            2         1       1    0  38.0      1      0          PC 17599   
2            3         1       3    0  26.0      0      0  STON/O2. 3101282   
3            4         1       1    0  35.0      1      0            113803   
4            5         0       3    1  35.0      0      0            373450   

      Fare  Embarked  
0   7.2500         2  
1  71.2833         0  
2   7.9250         2  
3  53.1000         2  
4   8.0500         2

In [36]:
df.drop(['Ticket'],axis=1,inplace=True)

In [41]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

c:\Users\Deepak joshi\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [42]:
y_pred = model.predict(x_test)

In [43]:
y_pred

array([0, 1])

In [44]:
y_test

281    0
435    1
Name: Survived, dtype: int64

In [45]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [46]:
accuracy_score(y_test,y_pred)

1.0

In [47]:
accuracy_score

<function sklearn.metrics._classification.accuracy_score(y_true, y_pred, *, normalize=True, sample_weight=None)>

In [48]:
confusion_matrix(y_test,y_pred)

array([[1, 0],
       [0, 1]])

In [49]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2



In [50]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    0  38.0      1      0  71.2833         0
2            3         1       3    0  26.0      0      0   7.9250         2
3            4         1       1    0  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2

KNN - K neararest neighbour

In [51]:
x_train

PassengerId  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
39            40       3    0  14.000000      1      0  11.2417         0
418          419       2    1  30.000000      0      0  13.0000         2
585          586       1    0  18.000000      0      2  79.6500         2
804          805       3    1  27.000000      0      0   6.9750         2
343          344       2    1  25.000000      0      0  13.0000         2
..           ...     ...  ...        ...    ...    ...      ...       ...
107          108       3    1  29.699118      0      0   7.7750         2
271          272       3    1  25.000000      0      0   0.0000         2
862          863       1    0  48.000000      0      0  25.9292         2
436          437       3    0  21.000000      2      2  34.3750         2
103          104       3    1  33.000000      0      0   8.6542         2

[887 rows x 8 columns]

In [52]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [53]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [54]:
from sklearn.neighbors import KNeighborsClassifier

In [55]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [56]:
y_pred_knn = knn_model.predict(x_test_scaled)

In [57]:
accuracy_score(y_test,y_pred_knn)

1.0

In [58]:
confusion_matrix(y_test,y_pred_knn)

array([[1, 0],
       [0, 1]])

In [59]:
x_test

PassengerId  Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
281          282       3    1  28.0      0      0    7.8542         2
435          436       1    0  14.0      1      2  120.0000         2

In [67]:
x_train

PassengerId  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
39            40       3    0  14.000000      1      0  11.2417         0
418          419       2    1  30.000000      0      0  13.0000         2
585          586       1    0  18.000000      0      2  79.6500         2
804          805       3    1  27.000000      0      0   6.9750         2
343          344       2    1  25.000000      0      0  13.0000         2
..           ...     ...  ...        ...    ...    ...      ...       ...
107          108       3    1  29.699118      0      0   7.7750         2
271          272       3    1  25.000000      0      0   0.0000         2
862          863       1    0  48.000000      0      0  25.9292         2
436          437       3    0  21.000000      2      2  34.3750         2
103          104       3    1  33.000000      0      0   8.6542         2

[887 rows x 8 columns]

In [60]:
from sklearn.naive_bayes import  GaussianNB

In [61]:
modle_kb = GaussianNB()

In [62]:
modle_kb.fit(x_train,y_train)

GaussianNB()

In [63]:
y_pred_kb = modle_kb.predict(x_test)

In [64]:
y_pred_kb

array([0, 1])

In [65]:
accuracy_score(y_test,y_pred_kb)

1.0

In [66]:
from sklearn.tree import DecisionTreeClassifier

In [67]:
model_Dt = DecisionTreeClassifier(random_state=42)

In [68]:
model_Dt.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [69]:
y_pred_Dt = model_Dt.predict(x_test_scaled)

In [70]:
accuracy_score(y_test,y_pred_Dt)

1.0

In [71]:
confusion_matrix(y_test,y_pred_Dt)

array([[1, 0],
       [0, 1]])

In [72]:
from sklearn.svm import SVC

In [73]:
model_svm = SVC(kernel='rbf')

In [74]:
model_svm.fit(x_train_scaled,y_train)

SVC()

In [77]:
y_pred_svc = model_svm.predict(x_test_scaled)

In [78]:
accuracy_score(y_test,y_pred_svc)

1.0